# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np

In [5]:
random_nparr = np.random.random((3,3,3))

random_nparr

array([[[0.21382556, 0.82164685, 0.55415473],
        [0.53867478, 0.10542479, 0.499776  ],
        [0.91381207, 0.23895206, 0.97874552]],

       [[0.13235976, 0.20627197, 0.06083863],
        [0.55052001, 0.48127527, 0.66129185],
        [0.47998717, 0.51304952, 0.48498503]],

       [[0.95705393, 0.98114833, 0.52629729],
        [0.57405912, 0.94776165, 0.99569904],
        [0.1934534 , 0.98676223, 0.59505933]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
nparr_5x5 = np.diag([1,2,3,4], -1)

nparr_5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
checker_board = np.zeros((8,8),dtype=int)

In [9]:
checker_board[1::2,::2] = 1
checker_board[::2,1::2] = 1

checker_board

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [11]:
normal_arr = np.random.random((5,5))

arr_max, arr_min = normal_arr.max(), normal_arr.min()

normal_arr = (normal_arr - arr_min) / (arr_max - arr_min)

normal_arr

array([[0.33499204, 0.63697048, 0.10364588, 0.40423227, 0.99058302],
       [0.04187549, 0.37373252, 0.        , 0.32038434, 0.22467469],
       [0.80002427, 0.09487886, 0.23169076, 0.74096109, 0.36398285],
       [0.62829388, 0.95024584, 0.32399419, 0.25782155, 1.        ],
       [0.14952509, 0.49167482, 0.25013374, 0.84285408, 0.1352879 ]])

# 5.  How to find common values between two arrays?

In [12]:
np_arr1 = np.array([2,4,8,10,20])
print("np_arr1: ",np_arr1)
np_arr2 = [10, 30, 40]
print("Array2: ",np_arr2)

print("Common values: ", np.intersect1d(np_arr1, np_arr2))

np_arr1:  [ 2  4  8 10 20]
Array2:  [10, 30, 40]
Common values:  [10]


# 6.How to get the dates of yesterday, today and tomorrow?

In [14]:
date_yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",date_yesterday)
date_today     = np.datetime64('today', 'D')
print("Today: ",date_today)
date_tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",date_tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

print("Equal? ", np.array_equal(arr1, arr2))

Equal?  True


In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,9,3])

print("Equal? ", np.array_equal(arr1, arr2))

Equal?  False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [22]:
np_arr = np.random.random(10)
np_arr[np_arr.argmax()] = 0

np_arr

array([0.73018339, 0.55584955, 0.        , 0.41740197, 0.28137584,
       0.63253854, 0.55891752, 0.75563077, 0.44966248, 0.39792443])

# 9. How to print all the values of an array?

In [25]:
np_arr = np.arange(11)

np_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 10.Subtract the mean of each row of a matrix

In [31]:
arr_orig = np.arange(12).reshape(3,4)

arr_orig

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr_result = arr_result - arr_orig.mean(axis=1, keepdims = True)

arr_result

array([[-1.5],
       [-5.5],
       [-9.5]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [40]:
#given vector
arr_given = np.random.randint(1,5,5)
print("Given vector:", arr_given)
arr_second = np.random.randint(arr_given)
arr_result = []
arr_second.sort()
for i in arr_second:
    if i not in arr_result:
        arr_result.append(i)

for j in arr_result:
    arr_given[j] += 1

Given vector: [4 1 3 2 3]


In [41]:
print("Indexing vector:", arr_second)
print("Result:",arr_given)

Indexing vector: [0 0 1 2 2]
Result: [5 2 4 2 3]


# 12.How to get the diagonal of a dot product?

In [42]:
X = [[10,20],[100,200]]
Y = [[5,10],[10,20]]
Z = np.diag(np.dot(X,Y))
Z

array([ 250, 5000])

# 13.How to find the most frequent value in an array?

In [46]:
arr1 = np.random.randint(0, 10, 20)
print("Original array:")
print(arr1)
print("Most frequent value in the above array:")
print(np.bincount(arr1).argmax())

Original array:
[2 5 3 2 8 1 1 1 4 0 4 4 3 7 0 7 7 6 1 7]
Most frequent value in the above array:
1


# 14.How to get the n largest values of an array

In [45]:
arr1 = np.arange(10)
print("Original array:")
print(arr1)
np.random.shuffle(arr1)
n = 1
print("Largest value of the array is",arr1[np.argsort(arr1)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest value of the array is [9]


# 15.How to create a record array from a regular array?

In [44]:
arr1=np.array(['ONE','TWO','THREE'])
arr2=np.array([1,2,3])
result= np.core.records.fromarrays([arr1, arr2])
print(result[0])
print(result[1])
print(result[2])

('ONE', 1)
('TWO', 2)
('THREE', 3)
